#!/bin/sh

# This script is used to play qolibri's audio and copy the file to clipboard.
# set 'qolibri-play' in Qolibri: Settings > Options > External Program
# You'll be able to play the audio in qolibri and paste the audio in Anki.

# You may choose any directory instead of '/tmp'
# Just make sure there are no whitespace or special characters in the path

filepath=/tmp/$(basename "$1")
ln "$1" "$filepath" || ln -s "$1" "$filepath"
echo "file://$filepath" | xclip -i -sel c -t "text/uri-list"
xdg-open "$filepath"
