#!/bin/sh

### This script records audio played by you computer as saves it in the current
### directory. It is designed to work with Anki and any window manager. 
### Need xclip and alsa/pulseaudio installed.
### Optionally, you man use ffmpeg, sox and a notification-daemon

# The name of your file contains a timestamp.
# You may change the extension as you wish.
OUTPUT="record_$(date +%F_%T).wav"

# Your recording device.
# Consult the appropriate one by using the command 'aplay -l'(ALSA) or
# 'pavucontrol' (Pulseaudio), or the file '$HOME/.asoundrc' (ALSA)
RECORDING_DEVICE=looprec

# Program used for recording; 'ffmpeg' or 'arecord'
COMMAND=arecord

# If it's already recording, finish recording.
if [ $(pgrep $COMMAND) ];then
        pkill $COMMAND
        exit 0
else
        # Send a notification and start recording.
        # It's possible to use 'ffmpeg' or 'arecord' to record. In case you
        # enable ffmpeg, set  '-f alsa' or '-f pulse'.
        notify-send "Recording audio." &
        if [ $COMMAND=arecord ]; then
            arecord -f cd -D "$RECORDING_DEVICE" "$OUTPUT"
        else
            ffmpeg -f alsa -i "$RECORDING_DEVICE" "$OUTPUT"
        fi
fi

# Check if SOX is installed and remove silence at the beginning and end.
if [ $(which sox) ];then
    mv $PWD/$OUTPUT $PWD/input.wav
    sox $PWD/input.wav $PWD/$OUTPUT silence 1 0.1 0.1% reverse silence 1 0.1 0.1% reverse
    rm $PWD/input.wav
fi

# Send the audio file's path to your clipboard, so that you can paste with
# Ctrl+v in Anki.
echo "file://$PWD/$OUTPUT" | xclip -i -selection clipboard -t "text/uri-list"
notify-send "Copied $PWD/$OUTPUT to the clipboard."
