#!/bin/sh

### This script records audio played by you computer as saves it in the current
### directory. It is designed to work with Anki and any window manager. 
### Need xclip installed.
### Optionally, you may use ffmpeg, sox and a notification-daemon.

# The name of your file contains a timestamp.
# You may change the path or extension as you wish.
# 'arecord' works with .wav only
FORMAT='wav'
OUTPUT="/tmp/tmpfs/record_$(date +%F_%T).$FORMAT"

# Your recording device.
# Consult the appropriate one by using the command 'aplay -l'(ALSA) or
# 'pavucontrol' (Pulseaudio), or the file '$HOME/.asoundrc' (ALSA)
RECORDING_DEVICE=looprec

# Program used for recording; 'ffmpeg' or 'arecord'
COMMAND=arecord
if ! [ $COMMAND = arecord -o $COMMAND = ffmpeg ]; then
    echo "Command Error\nChoose an appropriate command."
    exit 1
fi

# If it's already recording, finish recording.
if [ $(pgrep $COMMAND) ];then
        echo "Stopping recording audio."
        pkill $COMMAND
        exit 0
else
        # Send a notification and start recording.
        # It's possible to use 'ffmpeg' or 'arecord' to record. In case you
        # enable ffmpeg, set  '-f alsa' or '-f pulse'.
        notify-send "Recording audio." &
        echo "Recording audio.\n"
        if [ $COMMAND = arecord ]; then
            arecord -f cd -D "$RECORDING_DEVICE" "$OUTPUT"
        else
            ffmpeg -f alsa -i "$RECORDING_DEVICE" "$OUTPUT"
        fi
fi

# Check if SOX is installed and remove silence at the beginning and end.
if [ $(which sox) -a -f "$OUTPUT" ];then
    echo "Removing silence at both ends."
    DESTPATH=$(dirname "$OUTPUT")
    TEMP_INPUT="$DESTPATH"/input."$FORMAT"
    mv "$OUTPUT" "$TEMP_INPUT"
    sox "$TEMP_INPUT" "$OUTPUT" silence 1 0.1 0.1% reverse silence 1 0.1 0.1% reverse
    rm "$TEMP_INPUT"
fi

# Send the audio file's path to your clipboard, so that you can paste with
# Ctrl+v in Anki.
echo "file://$OUTPUT" | xclip -i -selection clipboard -t "text/uri-list"
echo "Copied $OUTPUT to the clipboard."
notify-send "Copied $OUTPUT to the clipboard."
