#!/bin/sh

# Take a screenshot and use tesseract to infer japanese text.

help_msg(){
        echo "\tTake a screenshot from a text and have its content copied to \
        the clipboard."
        echo "\t-H looks up for horizontal text (jpn)."
        echo "\t-h show this message."
}

# You may choose your language here. Use 'tesseract --list-langs'.
# YOu might need to install other languages's scripts.
# Defaults to japanese vertical text.
lang=jpn_vert

while getopts "hH" OPTION; do
    case $OPTION in
        H)  lang=jpn;; # horizontal text
        h|*) help_msg && exit 0;;
    esac
done

import -monochrome png:- | \
tesseract -l $lang stdin stdout | \
paste -s | tr -d [:blank:] | xclip -i -sel c
